//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dha5x5_STTE.rc
//
#define IDHARDWARE                      3
#define IDC_DAYMODE                     11
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DHA5X5_STTE_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_MM_DLG                      129
#define IDD_BRT_DLG                     130
#define IDD_MAINT_DLG                   131
#define IDR_MENU_MM                     132
#define IDD_STTE_CONFIG_DLG             133
#define IDD_UNIT_SEL_DLG                134
#define IDR_MENU_BRT_BUILDER            135
#define IDD_BRTFBK_CALIB_DLG            136
#define IDD_COM_DLG                     139
#define IDD_GENERATE_BRT_DLG            149
#define IDD_LOADER_DLG                  150
#define IDD_EDIT_IP_DLG                 159
#define IDD_LCDBRT_BUILDER_DLG          175
#define IDD_BRT_BUILDER_DLG             175
#define IDD_ENH_MAINT_DLG               176
#define IDC_RADIO_DAY                   1000
#define IDC_RADIO_NIGHT                 1001
#define IDC_LIST_COMS                   1001
#define IDC_EDIT_BRT                    1002
#define IDC_BUT_RESCAN                  1002
#define IDC_SLIDER_BRT                  1003
#define IDC_CHECK_FANONOFF              1004
#define IDC_STATIC_LUMINANCE_SENSOR     1005
#define IDC_RADIO_FANMANUAL             1006
#define IDC_RADIO_FANAUTO               1007
#define IDC_STATIC_BACKLIGHT_TEMPERATURE 1008
#define IDC_CHECK_STARTSTTE             1009
#define IDC_STATIC_LAMP_CONTROL_STATUS  1010
#define IDC_STATIC_BIT_STATUS           1011
#define IDC_CHECK_STARTSTTE2            1011
#define IDC_CHECK_HTR_ENABLE            1011
#define IDC_STATIC_FAN_STATUS           1012
#define IDC_IPADDRESS                   1012
#define IDC_STATIC_HEATER_STATUS        1013
#define IDC_STATIC_SW_VERSION           1014
#define IDC_STATIC_LUMINANCE_LEVEL      1015
#define IDC_STATIC_BIT1                 1016
#define IDC_BRT_TX                      1017
#define IDC_BRTRETURN                   1018
#define IDC_CHECK_DOUT_RESET            1018
#define IDC_FAN_TX                      1019
#define IDC_FANRETURN                   1020
#define IDC_CHECK_DOUT_GAMMASEL1        1020
#define IDC_STATIC_BIT2                 1021
#define IDC_DEFAULTWARMSTART            1022
#define IDC_CHECK_DOUT_GAMMASEL2        1022
#define IDC_DEFAULTWARMSTARTRET         1023
#define IDC_CHECK_DOUT_SHUTDOWN         1023
#define IDC_BUT_CFG_PROGRAM             1023
#define IDC_STATIC_BIT3                 1024
#define IDC_PROG_LOADER                 1024
#define IDC_STATIC_BIT4                 1025
#define IDC_STATIC_TARGET               1025
#define IDC_STATIC_BIT5                 1026
#define IDC_BUT_CFG_VERIFY              1026
#define IDC_DAYMODERET                  1027
#define IDC_CHECK_DOUT_SPARE1           1027
#define IDC_BUT_CFG_ERASE               1027
#define IDC_NIGHTMODERET                1028
#define IDC_CHECK_DOUT_SPARE2           1028
#define IDC_BUT_CFG_READINFO_FROMFILE   1028
#define IDC_RESTARTRET                  1029
#define IDC_RADIO_VIDEO_PATTERN_GEN     1029
#define IDC_STATIC_BIT6                 1030
#define IDC_BUT_STOP                    1030
#define IDC_NIGHTMODE                   1031
#define IDC_COMBO_VIDEO_PATTERN         1031
#define IDC_BUT_GPH_VERIFY              1031
#define IDC_RESTART                     1032
#define IDC_AUTOTEST                    1033
#define IDC_INVALID_COMMAND             1033
#define IDC_BUT_CNFUSR_PROGRAM          1033
#define IDC_READLUMINANCE               1034
#define IDC_LIST_CFG_INFO               1034
#define IDC_READBACKTEMP                1035
#define IDC_READLAMPSTATUS              1036
#define IDC_READBITSTATUS               1037
#define IDC_BUT_CFG_READINFO_FROMMEM    1037
#define IDC_FANSTATUS                   1038
#define IDC_READFANSTATUS               1038
#define IDC_BUT_CFG_READ                1038
#define IDC_HEATERSTATUS                1039
#define IDC_READHEATERSTATUS            1039
#define IDC_READSWVERSION               1040
#define IDC_READRUMINANCELEV            1041
#define IDC_READLUMINANCELEV            1041
#define IDC_STATIC_COMPORT              1042
#define IDC_DEF_WARM_START_COMMAND      1042
#define IDC_BUT_MM                      1043
#define IDC_TAB_GRAPH                   1044
#define IDC_BUT_MAINT                   1044
#define IDC_BUT_PROG                    1045
#define IDC_STATIC_BIT7                 1045
#define IDC_BUT_VERIFY                  1046
#define IDC_STATIC_BIT8                 1046
#define IDC_PROG_STATUS                 1047
#define IDC_UNREC_COMMAND               1047
#define IDC_TRACE                       1048
#define IDC_BUT_POLL                    1048
#define IDC_INVALID_COMMAND3            1048
#define IDC_TIMEOUT_COMMAND             1048
#define IDC_LIST_NODES                  1049
#define IDC_BUT_READ                    1049
#define IDC_BUT_LOADER                  1049
#define IDC_EDIT_NODE                   1050
#define IDC_NOOP_COMMAND                1050
#define IDC_EDIT2                       1051
#define IDC_EDIT_VALUE                  1051
#define IDC_DAY_WARM_START_COMMAND      1051
#define IDC_BUT_INSERT                  1052
#define IDC_DAY_WARM_START_COMMAND2     1052
#define IDC_NIGHT_WARM_START_COMMAND    1052
#define IDC_BUT_REMOVE                  1053
#define IDC_CHECK_LOGON                 1055
#define IDC_LIST_ANALOGS                1056
#define IDC_CHECK_LCD_ENABLE            1056
#define IDC_EDIT_PWM1                   1057
#define IDC_RADIO_VIDEO_EXT_PLAYER      1057
#define IDC_EDIT_PWM2                   1058
#define IDC_STATIC_STATUS               1058
#define IDC_STATIC_PAT_COL1             1058
#define IDC_BUT_GENERATE_LCDPWM         1058
#define IDC_LIST_ANALOGS2               1058
#define IDC_LIST_BIT                    1058
#define IDC_EDIT_PWM3                   1059
#define IDC_STATIC_PAT_RGB1             1059
#define IDC_EDIT_PWM4                   1060
#define IDC_STATIC_PAT_COL2             1060
#define IDC_BUT_IMPORT_LCDPWM           1060
#define IDC_EDIT_VDC1                   1061
#define IDC_STATIC_PAT_RGB2             1061
#define IDC_EDIT_VDC2                   1062
#define IDC_BUT_EXPORT_LCDPWM           1062
#define IDC_EDIT_VDC3                   1063
#define IDC_STATIC_PAT_COL3             1063
#define IDC_STATIC_PAT_MCOL1            1063
#define IDC_EDIT_VDC4                   1064
#define IDC_BUT_CNFUSR_VERIFY           1064
#define IDC_CHECK1                      1065
#define IDC_CHECK_HEATER                1065
#define IDC_CHECK_AUTOREAD              1065
#define IDC_BUT_CNFUSR_ERASE            1065
#define IDC_BUT_BITLOG_ERASE            1065
#define IDC_SPIN_BRT                    1066
#define IDC_BUT_CNFUSR_READ             1066
#define IDC_CHECK_DAY                   1066
#define IDC_BUT_BITLOG_READ             1066
#define IDC_SPIN_PWM1                   1067
#define IDC_SPIN_PWM2                   1068
#define IDC_EDIT_CURRLOFAN              1068
#define IDC_EDIT_CURROFFFAN             1068
#define IDC_SPIN_PWM3                   1069
#define IDC_EDIT_CURRONFAN_LO           1069
#define IDC_SPIN_PWM4                   1070
#define IDC_EDIT_CURRONFAN_LO2          1070
#define IDC_EDIT_CURRONFAN_HI           1070
#define IDC_STATIC_IPADD                1070
#define IDC_SPIN_VDC1                   1071
#define IDC_STATIC_HTR_STAT1            1071
#define IDC_SPIN_VDC2                   1072
#define IDC_BUTTON1                     1072
#define IDC_BUT_DEBUG                   1072
#define IDC_BUT_SET_IP                  1072
#define IDC_BUT_UNIT1                   1072
#define IDC_BUT_CALIB_BRT_FEEDBACK      1072
#define IDC_SPIN_VDC3                   1073
#define IDC_STATIC_HTR_STAT2            1073
#define IDC_STATIC_COM                  1073
#define IDC_BUT_UNIT2                   1073
#define IDC_BUT_REBOOT                  1073
#define IDC_SPIN_VDC4                   1074
#define IDC_STATIC_DIN_BIT_OUT          1074
#define IDC_IPADD_STTE                  1074
#define IDC_STATIC_DIN_BIT_EVENT        1075
#define IDC_EDIT_SN                     1075
#define IDC_STATIC_COM2                 1075
#define IDC_BUT_STTE_CONFIG             1076
#define IDC_BUT_SET_SN                  1076
#define IDC_COMBO_SPEED                 1076
#define IDC_STATIC_AD590_HEX            1077
#define IDC_COMBO_POT                   1077
#define IDC_STATIC_AD590_HEX2           1078
#define IDC_STATIC_AD590_TEMP           1078
#define IDC_CHECK_CONNECT               1078
#define IDC_STATIC_IPADD2               1079
#define IDC_STATIC_LOG_PATH             1079
#define IDC_SLIDER_DUTY                 1079
#define IDC_SLIDER_CURRENT              1080
#define IDC_STATIC_COM3                 1081
#define IDC_STATIC_ETI                  1081
#define IDC_EDIT_DUTY                   1082
#define IDC_EDIT_DUTY2                  1083
#define IDC_EDIT_CURRENT                1083
#define IDC_STATIC_ETI2                 1084
#define IDC_STATIC_PAT_MCOL2            1084
#define IDC_OPER_BRT_MODE               1085
#define IDC_COMBO_POT2                  1086
#define IDC_COMBO_MNT_OPERBRT           1086
#define IDC_EDIT_CODE                   1086
#define IDC_EDIT_NAME                   1087
#define IDC_PROGRESS1                   1087
#define IDC_PROG_CALIB                  1087
#define IDC_EDIT_DATE                   1088
#define IDC_STATIC_BIT6_LABEL           1088
#define IDC_EDIT_AUTHOR                 1089
#define IDC_STATIC_CODE                 1089
#define IDC_STATIC_CODE2                1090
#define IDC_STATIC_INTREV               1090
#define IDC_TAB_BRT_DN                  1091
#define IDC_TRACE_LCDPWM                1425
#define IDC_TRACE_LCDVOLT               1426
#define IDC_SLIDER_LCDBRT_CURSOR        1432
#define IDC_STATIC_LCDPWM_STEP          1433
#define IDC_STATIC_LCDPWM_DUTY          1434
#define IDC_LIST_LCDBRT_NODES           1435
#define IDC_STATIC_LCDCURR              1436
#define IDC_EDIT_LCDBRT_NODE            1437
#define IDC_EDIT_LCDBRT_VALUE           1438
#define IDC_BUT_INSERT_LCDBRT_NODE      1439
#define IDC_BUT_REMOVE_LCDBRT_NODE      1440
#define IDC_STATIC_FILE_PATH            1441
#define IDC_EDIT_GAMMA                  3006
#define IDC_EDIT_MIN_DUTY               3007
#define IDC_EDIT_MAX_DUTY               3008
#define IDC_EDIT_MAX_STEP               3009
#define IDC_EDIT_MIN_STEP               3010
#define ID_FILE_OPEN32771               32771
#define ID_FILE_SAVE32772               32772
#define ID_MENUFILE_OPEN                32773
#define ID_MENUFILE_SAVE                32774
#define ID_FILE_IMPORTFULL              32775
#define ID_FILE_OPEN32776               32776
#define ID_FILE_SAVE32777               32777
#define ID_FILE_SAVEAS                  32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1090
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
